name: Generate QR Codes
on: [push]
jobs:
  generate-qr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate QR Codes
        run: |
          pip install qrcode[pil]
          python -c "import qrcode; qrcode.make(f'https://${{ github.repository_owner }}.github.io/cc-qr/ground-cc.jpg').save('ground-qr.png')"
          python -c "import qrcode; qrcode.make(f'https://${{ github.repository_owner }}.github.io/cc-qr/coated-cc.jpg').save('coated-qr.png')"
      - name: Upload QR Codes
        uses: actions/upload-artifact@v4
        with:
          path: |
            ground-qr.png
            coated-qr.png
